### ISSUE TITLE
VCMod/GAuto passengers can control the lights/sirens

### ISSUE THREAD

**Issue by ischmal** [photonle/Photon-v2#2]
Known issue relating to Photon's driver detection.

**Comment by LambdaGaming** [comment]
GAuto is also affected by this. I can make adjustments on my end if needed.

**Comment by ischmal** [comment]
> GAuto is also affected by this. I can make adjustments on my end if needed.

Nah your code is fine, but thanks for the offer. Should be fixed soon.
